### ISSUE TITLE
NoCheatPlus support

### ISSUE THREAD

**Issue by andris155** [nulli0n/ExcellentEnchants#1]
Description
The NoCheatPlus blocks some enchants. Example: Tunel.

Versions
Paper 1.17.1 build 165
NexEngine 2.0.7.4
ExcellentEnchants 3.0.3.1
NoCheatPlus: https://www.mc-market.org/resources/475/

Reproduce
1. Use Tunel enchanted tool if NoCheatPlus installed.
2. NoCheatPlus deny break multiple blocks.

Expected behavior
ExcellentEnchants support the NoCheatPlus and works enchants with NoCheatPlus plugin.

**Comment by nulli0n** [comment]
Done

**Comment by andris155** [comment]
Thanks!
