### ISSUE TITLE
Telekinesis enchant and Slimefun items

### ISSUE THREAD

**Issue by andris155** [nulli0n/ExcellentEnchants#14]
If I break a Slimefun plugin block with a telekinesis enchanted tool, the Slimefun plugin block converted to the normal block.
Paper build 237
ExcellentEnchants version 3.0.6
https://github.com/Slimefun/Slimefun4
https://www.youtube.com/watch?v=UYCqqXKIvkY

**Comment by nulli0n** [comment]
Try new version.

**Comment by andris155** [comment]
The new version not fixed this bug.

**Comment by nulli0n** [comment]
There is nothing I can do more. Ask plugin author to properly cancel block event.

**Comment by andris155** [comment]
The error here is not to put the item in the inventory, but to lose the custom name, lore, and NBT from item.

**Comment by nulli0n** [comment]
Once again, enchantment have effect only when block drops is not cancelled. The main problem is in slimefun plugin. I can't fix it.
