### ISSUE TITLE
Telekinesis enchant and SuperLuckyBlock duplicate

### ISSUE THREAD

**Issue by andris155** [nulli0n/ExcellentEnchants#15]
If I break a Lucky block with a telekinesis enchanted tool, the plugin place a lucky block to the inventory.
Paper build 237
ExcellentEnchants version 3.0.6
https://www.spigotmc.org/resources/superluckyblock-1-13-2-1-17-the-luckyblock-plugin-that-gives-you-full-control.48837/
https://www.youtube.com/watch?v=oSejudlrrVo

**Comment by nulli0n** [comment]
Try new version.

**Comment by andris155** [comment]
The new version not fixed this bug.

**Comment by nulli0n** [comment]
There is nothing I can do more. Ask plugin author to properly cancel block event.
