### ISSUE TITLE
Lure 5 not working

### ISSUE THREAD

**Issue by MinerCoffee** [nulli0n/ExcellentEnchants#17]
Lore 5 showing up as lore 3. It looks like the level five it not working.

**Comment by nulli0n** [comment]
What

**Comment by MinerCoffee** [comment]
When enchanting with lore 5 it does not work it, makes lore 3 on the tool.

**Comment by nulli0n** [comment]
What is 'lore'?

**Comment by MinerCoffee** [comment]
I meant lure.

**Comment by nulli0n** [comment]
It does nothing with default enchantments.

**Comment by MinerCoffee** [comment]
So lure 5 does the same as lure 3? Because your plugin bring lure 5 as option.

**Comment by MinerCoffee** [comment]
You it might be a different plugin for enchantments we have on the server.
