### ISSUE TITLE
 How to translate conflict enchantment

### ISSUE THREAD

**Issue by Alinen1501** [nulli0n/ExcellentEnchants#18]
What method should I use to translate conflicting enchantments. 
Or can you add them?
![Screenshot 2021-09-08 130916](https://user-images.githubusercontent.com/68199246/132450174-dc370c16-3dd4-416b-942e-843d9b0de6b3.png)

**Comment by nulli0n** [comment]
Check in /NexEngine/lang

**Comment by Alinen1501** [comment]
Do I need to add it manually? Because I only see the ID of the original item. I don’t see the ID of the enchantment.

**Comment by Alinen1501** [comment]
Or can you add conflicts options in lang for me to translate? Because I really can’t find where to translate

![Screenshot 2021-09-09 135051](https://user-images.githubusercontent.com/68199246/132630468-39687089-408f-4353-bf33-5b36409b81a2.png)

**Comment by Alinen1501** [comment]
Or can I turn off the judgment of conflict enchanting?

**Comment by Alinen1501** [comment]
And how do I change the equipment that can be enchanted? For example, I want the enchantment that can only be used on the torso to be used on the shoes.

**Comment by Alinen1501** [comment]
Thanks
