### ISSUE TITLE
[FEATURE REQUEST] Enchantment Permission Nodes

### ISSUE THREAD

**Issue by Tim-Rambo** [nulli0n/ExcellentEnchants#25]
Permission per enchantment.
Why would I want this?
Because then we have more control over the custom enchantments.
And you would be able to setup shops for gaining access to the enchants via the enchantment table for example.
Like you would have to pay X to research enchantment X for example.

Thank you for reading :)

**Comment by nulli0n** [comment]
No, sorry.
