### ISSUE TITLE
Destroyed blocks will disappear.

### ISSUE THREAD

**Issue by CapacityDown** [nulli0n/ExcellentEnchants#26]
If you destroy a block while holding an axe in your hand that grants both Telekinesis and Silk Chest, the destroyed block will disappear completely.
I haven't tried to see what happens with other tools, but as far as axes are concerned, the block always disappears when these two enchantments are granted.

**Comment by nulli0n** [comment]
Should be fixed in the latest version.

**Comment by nulli0n** [comment]
Fixed.
