### ISSUE TITLE
InvocationTargetException

### ISSUE THREAD

**Issue by Bloodlex** [nulli0n/ExcellentEnchants#4]
Hey, I have following error in console:

Current version: 3.0.4.1
Server version: Purpur version git-Purpur-1060 (MC: 1.16.5)

12.08 08:53:17 [Server] WARN Loaded class su.nightexpress.excellentenchants.nms.V1_16_R3 from ExcellentEnchants v3.0.4 which is not a depend, softdepend or loadbefore of this plugin.
12.08 08:53:17 [Server] WARN java.lang.reflect.InvocationTargetException
12.08 08:53:17 [Server] WARN at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
12.08 08:53:17 [Server] WARN at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
12.08 08:53:17 [Server] WARN at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
12.08 08:53:17 [Server] WARN at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
12.08 08:53:17 [Server] WARN at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
12.08 08:53:17 [Server] WARN at su.nightexpress.excellentenchants.manager.EnchantRegister.init(EnchantRegister.java:149)
12.08 08:53:17 [Server] WARN at su.nightexpress.excellentenchants.manager.EnchantRegister.<clinit>(EnchantRegister.java:93)
12.08 08:53:17 [Server] WARN at su.nightexpress.excellentenchants.manager.EnchantManager.onLoad(EnchantManager.java:45)
12.08 08:53:17 [Server] WARN at su.nexmedia.engine.api.manager.AbstractManager.setup(AbstractManager.java:21)
12.08 08:53:17 [Server] WARN at su.nightexpress.excellentenchants.ExcellentEnchants.enable(ExcellentEnchants.java:46)
12.08 08:53:17 [Server] WARN at su.nexmedia.engine.NexPlugin.loadManagers(NexPlugin.java:182)
12.08 08:53:17 [Server] WARN at su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:75)
12.08 08:53:17 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
12.08 08:53:17 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
12.08 08:53:17 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
12.08 08:53:17 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
12.08 08:53:17 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
12.08 08:53:17 [Server] WARN at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:264)
12.08 08:53:17 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1070)
12.08 08:53:17 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
12.08 08:53:17 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:831)
12.08 08:53:17 [Server] WARN Caused by: java.lang.NullPointerException: Cannot invoke "su.nexmedia.engine.utils.eval.javaluator.EvaluationContext.getError(String, su.nexmedia.engine.utils.eval.javaluator.Token)" because "evaluationContext" is null
12.08 08:53:17 [Server] WARN at su.nexmedia.engine.utils.eval.javaluator.DoubleEvaluator.toValue(DoubleEvaluator.java:304)
12.08 08:53:17 [Server] WARN at su.nexmedia.engine.utils.eval.javaluator.DoubleEvaluator.toValue(DoubleEvaluator.java:58)
12.08 08:53:17 [Server] WARN at su.nexmedia.engine.utils.eval.javaluator.AbstractEvaluator.output(AbstractEvaluator.java:124)
12.08 08:53:17 [Server] WARN at su.nexmedia.engine.utils.eval.javaluator.AbstractEvaluator.evaluate(AbstractEvaluator.java:376)
12.08 08:53:17 [Server] WARN at su.nexmedia.engine.utils.eval.javaluator.AbstractEvaluator.evaluate(AbstractEvaluator.java:220)
12.08 08:53:17 [Server] WARN at su.nexmedia.engine.utils.eval.Evaluator.javaluator(Evaluator.java:24)
12.08 08:53:17 [Server] WARN at su.nexmedia.engine.utils.eval.Evaluator.eval(Evaluator.java:17)
12.08 08:53:17 [Server] WARN at su.nexmedia.engine.manager.leveling.Scaler.<init>(Scaler.java:42)
12.08 08:53:17 [Server] WARN at su.nightexpress.excellentenchants.manager.object.EnchantScaler.<init>(EnchantScaler.java:10)
12.08 08:53:17 [Server] WARN at su.nightexpress.excellentenchants.manager.enchants.tool.EnchantTelekinesis.<init>(EnchantTelekinesis.java:32)
12.08 08:53:17 [Server] WARN ... 21 more

**Comment by Bloodlex** [comment]
Any update on this one?

**Comment by nulli0n** [comment]
Reset config for Telekinesis enchant.
